name: CI/CD to GitHub Pages

on:
  push:
    branches: [ "main" ] # only when we push to main

# Config the GITHUB_TOKEN permissions 
permissions:
  contents: read
  pages: write
  id-token: write

# Avoid simultaneous executions if you make pushes very frequently
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest # runs on a Linux virtual machine
    steps:
      - name: 📥 Download source code
        uses: actions/checkout@v5

      - name: 🟢 Config Node.js environment
        uses: actions/setup-node@v5
        with:
          node-version: 24
          cache: 'npm' # Dependency caching for fast future builds

      - name: 📦 Install dependencies
        run: npm ci # Clean and strict installation based on package-lock.json

      - name: 🧪 Run unit tests
        run: npm run test:run

      - name: 🏗️ Compile application (Build)
        run: npm run build

      - name: ⚙️ Config GitHub Pages
        uses: actions/configure-pages@v5

      - name: 📤 Upload the production output (Artifact)
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist' # Upload only the folder compiled by Vite

      - name: 🚀 Deploy
        id: deployment
        uses: actions/deploy-pages@v4